name: Python Application

# Menentukan kapan alur kerja dijalankan
on:
  push:
    branches:
      - main  # Alur kerja dijalankan saat ada perubahan di branch 'main'
  pull_request:
    branches:
      - main  # Atau saat ada pull request ke branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Menentukan runner yang digunakan (ubuntu-latest di sini)

    steps:
      # Langkah pertama: checkout kode dari repositori
      - name: Checkout code
        uses: actions/checkout@v3  # Mengambil kode dari repositori

      # Langkah kedua: setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Menentukan versi Python yang digunakan

      # Langkah ketiga: Install dependensi
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Memperbarui pip
          pip install -r requirements.txt  # Menginstal dependensi dari file requirements.txt

      # Langkah keempat: Menjalankan skrip atau aplikasi
      - name: Run program
        run: |
          python app_modeltrain.py  # Gantilah dengan nama file Python yang sesuai, misalnya 'train_model.py'
